var k_ = {
	CTRL: 17,
	CTRLRIGHT: 18,
	SHIFT: 16,
	RETURN: 13,
	BACKSPACE: 8,
	ALT: 18,
	SPACE: 32,
	WIN: 91,
	FN: null,
	UP: 38,
	DOWN: 40,
	LEFT: 37,
	RIGHT: 39,
	ESC: 27,
	DEL: 46,
	F1: 112,
	F2: 113,
	F3: 114,
	F4: 115,
	F5: 116,
	F6: 117,
	F7: 118,
	F8: 119,
	F9: 120,
	F10: 121,
	F11: 122,
	F12: 123,
	TAB : 9,
	PAUSE_BREAK : 19,
	CAPS_LOCK : 20,
	ESCAPE : 27,
	PAGE_UP : 33,
	PAGE_DOWN : 34,
	END : 35,
	HOME : 36,
	LEFT_ARROW : 37,
	UP_ARROW : 38,
	RIGHT_ARROW : 39,
	DOWN_ARROW : 40,
	INSERT : 45,
	DELETE : 46,
	'0' : 48,
	'1' : 49,
	'2' : 50,
	'3' : 51,
	'4' : 52,
	'5' : 53,
	'6' : 54,
	'7' : 55,
	'8' : 56,
	'9' : 57,
	A : 65,
	B : 66,
	C : 67,
	D : 68,
	E : 69,
	F : 70,
	G : 71,
	H : 72,
	I : 73,
	J : 74,
	K : 75,
	L : 76,
	M : 77,
	N : 78,
	O : 79,
	P : 80,
	Q : 81,
	R : 82,
	S : 83,
	T : 84,
	U : 85,
	V : 86,
	W : 87,
	X : 88,
	Y : 89,
	Z : 90,
	LEFT_WINDOW : 91,
	RIGHT_WINDOW : 92,
	SELECT : 93,
	NUMPAD_0 : 96,
	NUMPAD_1 : 97,
	NUMPAD_2 : 98,
	NUMPAD_3 : 99,
	NUMPAD_4 : 100,
	NUMPAD_5 : 101,
	NUMPAD_6 : 102,
	NUMPAD_7 : 103,
	NUMPAD_8 : 104,
	NUMPAD_9 : 105,
	MULTIPLY : 106,
	ADD : 107,
	SUBTRACT : 109,
	DECIMAL_POINT : 110,
	DIVIDE : 111,
	F1 : 112,
	F2 : 113,
	F3 : 114,
	F4 : 115,
	F5 : 116,
	F6 : 117,
	F7 : 118,
	F8 : 119,
	F9 : 120,
	F10 : 121,
	F11 : 122,
	F12 : 123,
	NUM_LOCK : 144,
	SCROLL_LOCK : 145,
	SEMI_COLON : 186,
	EQUAL_SIGN : 187,
	COMMA : 188,
	DASH : 189,
	PERIOD : 190,
	FORWARD_SLASH : 191,
	GRAVE_ACCENT : 192,
	OPEN_BRACKET : 219,
	BACKSLASH : 220,
	CLOSEBRACKET : 221,
	SINGLE_QUOTE : 222
};

var keyNames = {};

for (var name in k_) {
	keyNames[k_[name]] = name;
}

var Applications = {
	photoshop_cs6: {
		title: 'Photoshop CS6',
		img: 'img/photoshop_cs6.png',
		link: 'http://www.adobe.com/de/products/photoshop.html',
		shortcuts: null
	},
	resharper_8: {
		title: 'JetBrains Resharper 8',
		img: 'img/resharper_8.png',
		link: 'http://www.jetbrains.com/resharper/',
		shortcuts: null
	},
	word_2013: {
		title: 'Microsoft Word 2013',
		img: 'img/word_2013.png',
		link: 'http://office.microsoft.com/de-de/word/',
		shortcuts: null
	},
	visualstudio_2013: {
		title: 'Microsoft Visual Studio 2013',
		img: 'img/visualstudio_2013.png',
		link: 'http://www.visualstudio.com/',
		shortcuts: null
	},
	emmet: {
		title: 'Emmet',
		img: 'img/emmet.png',
		link: 'http://emmet.io/',
		shortcuts: null
	}
};

Applications.photoshop_cs6.shortcuts = [
	{ img: 'img/photoshop_cs6/move.png', keys: [[k_.V]], name: 'Move Tool' },
	{ img: 'img/photoshop_cs6/magicwand.png', keys: [[k_.W]], name: 'Magic Wand Tool' },
	{ img: 'img/photoshop_cs6/crop.png', keys: [[k_.C]], name: 'Crop Tool' },
	{ img: 'img/photoshop_cs6/eyedropper.png', keys: [[k_.I]], name: 'Eyedropper Tool' },
	{ img: 'img/photoshop_cs6/spothealing.png', keys: [[k_.J]], name: 'Spothealing Tool' },
	{ img: 'img/photoshop_cs6/brush.png', keys: [[k_.B]], name: 'Brush Tool' },
	{ img: 'img/photoshop_cs6/clonestamp.png', keys: [[k_.S]], name: 'Clone Stamp Tool' },
	{ img: 'img/photoshop_cs6/historybrush.png', keys: [[k_.Y]], name: 'History Brush Tool' },
	{ img: 'img/photoshop_cs6/eraser.png', keys: [[k_.E]], name: 'Eraser Tool' },
	{ img: 'img/photoshop_cs6/gradient.png', keys: [[k_.G]], name: 'Gradient Tool' },
	{ img: 'img/photoshop_cs6/dodge.png', keys: [[k_.O]], name: 'Dodge Tool' },
	{ img: 'img/photoshop_cs6/pen.png', keys: [[k_.P]], name: 'Pen Tool' },
	{ img: 'img/photoshop_cs6/horizontaltype.png', keys: [[k_.T]], name: 'Horizontal Type Tool' },
	{ img: 'img/photoshop_cs6/pathselection.png', keys: [[k_.A]], name: 'Path Selection Tool' },
	{ img: 'img/photoshop_cs6/rectangle.png', keys: [[k_.U]], name: 'Rectangle Tool' },
	{ img: 'img/photoshop_cs6/hand.png', keys: [[k_.H]], name: 'Hand Tool' },
	{ img: 'img/photoshop_cs6/zoom.png', keys: [[k_.Z]], name: 'Zoom Tool'  }
];

Applications.resharper_8.shortcuts = [
	{ img: '', keys: [[k_.CTRL, k_.SHIFT, k_.ALT, k_.UP_ARROW]], name: 'Move code up'  },
	{ img: '', keys: [[k_.CTRL, k_.SHIFT, k_.ALT, k_.LEFT_ARROW]], name: 'Move code left'  },
	{ img: '', keys: [[k_.CTRL, k_.SHIFT, k_.ALT, k_.RIGHT_ARROW]], name: 'Move code right'  },
	{ img: '', keys: [[k_.CTRL, k_.SHIFT, k_.ALT, k_.DOWN_ARROW]], name: 'Move code down'  },
	{ img: '', keys: [[k_.CTRL, k_.SPACE]], name: 'Symbol code completion'  },
	{ img: '', keys: [[k_.CTRL, k_.ALT, k_.SPACE]], name: 'Smart code completion'  },
	{ img: '', keys: [[k_.SHIFT, k_.ALT, k_.SPACE]], name: 'Import symbol completion'  },
	{ img: '', keys: [[k_.CTRL, k_.SHIFT, k_.SPACE]], name: 'Parameter Info'  },
	{ img: '', keys: [[k_.CTRL, k_.SHIFT, k_.ALT, k_.SPACE]], name: 'Go to previous signature (in parameter info)'  },
	{ img: '', keys: [[k_.CTRL, k_.SHIFT, k_.F1]], name: 'Quick documentation'  },
	{ img: '', keys: [[k_.CTRL, k_.ALT, k_.RIGHT_ARROW]], name: 'Extend selection'  },
	{ img: '', keys: [[k_.CTRL, k_.ALT, k_.LEFT_ARROW]], name: 'Shrink selection'  },
	{ img: '', keys: [[k_.CTRL, k_.D]], name: 'Duplicate a line or selection'  },
	{ img: '', keys: [[k_.CTRL, k_.SHIFT, k_.OPEN_BRACKET]], name: 'Select containing declaration'  },
	{ img: '', keys: [[k_.CTRL, k_.ALT, k_.FORWARD_SLASH]], name: 'Comment with line comment'  },
	{ img: '', keys: [[k_.CTRL, k_.SHIFT, k_.FORWARD_SLASH]], name: 'Comment with block comment'  },
	{ img: '', keys: [[k_.ALT, k_.INSERT]], name: 'Generate code (constructors, properties, implementing/overriding members, etc.)'  },
	{ img: '', keys: [[k_.CTRL, k_.E], [k_.L]], name: 'Insert live template'  },
	{ img: '', keys: [[k_.CTRL, k_.E], [k_.U]], name: 'Surround with template'  },
	{ img: '', keys: [[k_.ALT, k_.INSERT]], name: 'Create file from template (in Solution Explorer)'  },
	{ img: '', keys: [[k_.CTRL, k_.SHIFT, k_.BACKSPACE]], name: 'Go to last edit location'  },
	{ img: '', keys: [[k_.CTRL, k_.COMMA]], name: 'View recent files'  },
	{ img: '', keys: [[k_.CTRL, k_.SHIFT, k_.COMMA]], name: 'View recent edits'  },
	{ img: '', keys: [[k_.CTRL, k_.ALT, k_.F7]], name: 'Go to related files'  },
	{ img: '', keys: [[k_.CTRL, k_.GRAVE_ACCENT]], name: 'View Bookmarks'  },
	{ img: '', keys: [[k_.CTRL, k_['2']]], name: 'Go to bookmark 2'  },
	{ img: '', keys: [[k_.CTRL, k_['5']]], name: 'Go to bookmark 5'  },
	{ img: '', keys: [[k_.CTRL, k_['8']]], name: 'Go to bookmark 8'  },
	{ img: '', keys: [[k_.CTRL, k_.SHIFT, k_['0']]], name: 'Set/remove bookmark 0'  },
	{ img: '', keys: [[k_.CTRL, k_.SHIFT, k_['1']]], name: 'Set/remove bookmark 1'  },
	{ img: '', keys: [[k_.CTRL, k_.SHIFT, k_['3']]], name: 'Set/remove bookmark 3'  }
];

Applications.word_2013.shortcuts = [
	{ img: 'img/word_2013/copy.png', keys: [[k_.CTRL, k_.C]] }
];

Applications.visualstudio_2013.shortcuts = [
	{ img: 'img/visualstudio_2013/save.png', keys: [[k_.CTRL, k_.S]]},
	{ img: 'img/visualstudio_2013/format.png', keys: [[k_.CTRL, k_.K],[k_.CTRL, k_.D]]}
];

